# Generated by Django 5.1.6 on 2025-04-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0021_alter_bankaccountmodel_account_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymodel',
            name='is_nonprofit',
            field=models.BooleanField(default=False),
        ),
    ]
