# Generated by Django 5.1.6 on 2025-04-05 05:49

import django.db.models.deletion
import django_ledger.io.io_core
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0023_alter_entitymodel_is_nonprofit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundModel',
            fields=[
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('document_prefix', models.CharField(max_length=3)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('hidden', models.BooleanField(default=False, verbose_name='Is Hidden')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Fund')),
            ],
            options={
                'verbose_name': 'Fund Model',
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=(django_ledger.io.io_core.IOMixIn, models.Model),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='fund',
            field=models.ForeignKey(help_text='Fund to be associated with this transaction.', null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.fundmodel', verbose_name='Fund'),
        ),
        migrations.AddIndex(
            model_name='transactionmodel',
            index=models.Index(fields=['fund'], name='django_ledg_fund_id_ceaefc_idx'),
        ),
        migrations.AddIndex(
            model_name='fundmodel',
            index=models.Index(fields=['active'], name='django_ledg_active_c7c619_idx'),
        ),
        migrations.AddIndex(
            model_name='fundmodel',
            index=models.Index(fields=['hidden'], name='django_ledg_hidden_ce1d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='fundmodel',
            index=models.Index(fields=['entity'], name='django_ledg_entity__2f6f67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundmodel',
            unique_together={('entity', 'document_prefix'), ('entity', 'slug')},
        ),
    ]
