# Generated by Django 5.1.6 on 2025-04-10 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0024_fundmodel_transactionmodel_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransactionmodel',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.fundmodel', verbose_name='Associated Fund'),
        ),
    ]
