# Generated by Django 5.1.6 on 2025-04-28 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0025_itemtransactionmodel_fund'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionmodel',
            name='django_ledg_fund_id_ceaefc_idx',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='fund',
        ),
        migrations.AddField(
            model_name='journalentrymodel',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.fundmodel', verbose_name='Associated Fund'),
        ),
    ]
