# Generated by Django 5.1.6 on 2025-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0026_remove_transactionmodel_django_ledg_fund_id_ceaefc_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentrymodel',
            index=models.Index(fields=['fund'], name='django_ledg_fund_id_289e56_idx'),
        ),
    ]
