# Generated by Django 5.1.6 on 2025-04-29 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0027_journalentrymodel_django_ledg_fund_id_289e56_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entitystatemodel',
            name='django_ledg_entity__eeae49_idx',
        ),
        migrations.AlterUniqueTogether(
            name='entitystatemodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entitystatemodel',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.fundmodel', verbose_name='Fund'),
        ),
        migrations.AlterUniqueTogether(
            name='entitystatemodel',
            unique_together={('entity_model', 'entity_unit', 'fund', 'fiscal_year', 'key')},
        ),
        migrations.AddIndex(
            model_name='entitystatemodel',
            index=models.Index(fields=['entity_model', 'fiscal_year', 'entity_unit', 'fund', 'key'], name='django_ledg_entity__aa3e9b_idx'),
        ),
    ]
