# Generated by Django 5.1.6 on 2025-04-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0028_remove_entitystatemodel_django_ledg_entity__eeae49_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedtransactionmodel',
            name='fund_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.fundmodel', verbose_name='Fund Model'),
        ),
    ]
