# Generated by Django 5.1.6 on 2025-04-30 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0029_stagedtransactionmodel_fund_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='closingentrytransactionmodel',
            name='unique_closing_entry',
        ),
        migrations.RemoveConstraint(
            model_name='closingentrytransactionmodel',
            name='unique_ce_opt_1',
        ),
        migrations.RemoveConstraint(
            model_name='closingentrytransactionmodel',
            name='unique_ce_opt_2',
        ),
        migrations.RemoveConstraint(
            model_name='closingentrytransactionmodel',
            name='unique_ce_opt_3',
        ),
        migrations.AddField(
            model_name='closingentrytransactionmodel',
            name='fund_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.fundmodel', verbose_name='Fund Model'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(fields=('closing_entry_model', 'account_model', 'unit_model', 'fund_model', 'activity'), name='unique_closing_entry'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('activity', None)), fields=('closing_entry_model', 'account_model', 'unit_model', 'fund_model'), name='unique_ce_opt_1'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('fund_model', None), ('unit_model', None)), fields=('closing_entry_model', 'account_model', 'activity'), name='unique_ce_opt_2'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('fund_model', None), ('unit_model', None), ('activity', None)), fields=('closing_entry_model', 'account_model'), name='unique_ce_opt_3'),
        ),
    ]
