# Generated by Django 5.1.6 on 2025-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0030_remove_closingentrytransactionmodel_unique_closing_entry_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='closingentrytransactionmodel',
            name='unique_ce_opt_1',
        ),
        migrations.RemoveConstraint(
            model_name='closingentrytransactionmodel',
            name='unique_ce_opt_2',
        ),
        migrations.RemoveConstraint(
            model_name='closingentrytransactionmodel',
            name='unique_ce_opt_3',
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('activity', None)), fields=('closing_entry_model', 'account_model', 'unit_model', 'fund_model'), name='unique_ce_opt_1a'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None)), fields=('closing_entry_model', 'account_model', 'fund_model', 'activity'), name='unique_ce_opt_1b'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('fund_model', None)), fields=('closing_entry_model', 'account_model', 'unit_model', 'activity'), name='unique_ce_opt_1c'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None), ('fund_model', None)), fields=('closing_entry_model', 'account_model', 'activity'), name='unique_ce_opt_2a'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('activity', None), ('fund_model', None)), fields=('closing_entry_model', 'account_model', 'unit_model'), name='unique_ce_opt_2b'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None), ('activity', None)), fields=('closing_entry_model', 'account_model', 'fund_model'), name='unique_ce_opt_2c'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None), ('fund_model', None), ('activity', None)), fields=('closing_entry_model', 'account_model'), name='unique_ce_opt_3'),
        ),
    ]
