# Generated by Django 5.1.6 on 2025-05-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0031_remove_closingentrytransactionmodel_unique_ce_opt_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentrymodel',
            name='receiving_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receiving_fund', to='django_ledger.fundmodel', verbose_name='Receiving Fund'),
        ),
        migrations.AddIndex(
            model_name='journalentrymodel',
            index=models.Index(fields=['receiving_fund'], name='django_ledg_receivi_09a074_idx'),
        ),
    ]
