# Generated by Django 5.1.6 on 2025-05-06 00:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0032_journalentrymodel_receiving_fund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransferModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('markdown_notes', models.TextField(blank=True, null=True, verbose_name='Markdown Notes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fund_transfer_number', models.SlugField(editable=False, max_length=20, verbose_name='Fund Transfer Number')),
                ('transfer_date', models.DateField(help_text='Date of the Fund Transfer.', verbose_name='Transfer Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('comment', models.TextField(blank=True, help_text='Any additional comment about the Fund Transfer.', null=True, verbose_name='Comment')),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='Fund Transfer Additional Info')),
                ('from_account', models.ForeignKey(help_text='Account from which the transfer is made.', on_delete=django.db.models.deletion.RESTRICT, related_name='fund_transfer_from_account', to='django_ledger.accountmodel', verbose_name='Source Account')),
                ('from_fund', models.ForeignKey(help_text='Fund from which the transfer is made.', on_delete=django.db.models.deletion.RESTRICT, related_name='fund_transfer_from_fund', to='django_ledger.fundmodel', verbose_name='Source Fund')),
                ('to_account', models.ForeignKey(help_text='Account to which the transfer is made.', on_delete=django.db.models.deletion.RESTRICT, related_name='fund_transfer_to_account', to='django_ledger.accountmodel', verbose_name='Destination Account')),
                ('to_fund', models.ForeignKey(help_text='Fund to which the transfer is made.', on_delete=django.db.models.deletion.RESTRICT, related_name='fund_transfer_to_fund', to='django_ledger.fundmodel', verbose_name='Destination Fund')),
            ],
            options={
                'verbose_name': 'Fund Transfer',
                'verbose_name_plural': 'Fund Transfers',
                'ordering': ['-updated'],
                'abstract': False,
                'indexes': [models.Index(fields=['fund_transfer_number'], name='django_ledg_fund_tr_9d3b8c_idx'), models.Index(fields=['from_fund'], name='django_ledg_from_fu_fedb77_idx'), models.Index(fields=['to_fund'], name='django_ledg_to_fund_f67124_idx')],
            },
        ),
    ]
