# Generated by Django 5.1.6 on 2025-05-06 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0033_fundtransfermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransfermodel',
            name='ledger',
            field=models.OneToOneField(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.ledgermodel', verbose_name='Ledger'),
            preserve_default=False,
        ),
    ]
