# Generated by Django 5.1.6 on 2025-05-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0034_fundtransfermodel_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundtransfermodel',
            name='comment',
        ),
        migrations.AddField(
            model_name='fundtransfermodel',
            name='fund_transfer_status',
            field=models.CharField(choices=[('created', 'created'), ('void', 'Void')], default='created', max_length=10, verbose_name='Fund Transfer Status'),
        ),
        migrations.AddIndex(
            model_name='fundtransfermodel',
            index=models.Index(fields=['fund_transfer_status'], name='django_ledg_fund_tr_90b08a_idx'),
        ),
        migrations.AddIndex(
            model_name='fundtransfermodel',
            index=models.Index(fields=['transfer_date'], name='django_ledg_transfe_acbbe9_idx'),
        ),
    ]
