# Generated by Django 5.1.6 on 2025-05-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0035_remove_fundtransfermodel_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransfermodel',
            name='date_void',
            field=models.DateField(blank=True, null=True, verbose_name='Void Date'),
        ),
    ]
