# Generated by Django 5.1.6 on 2025-05-22 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0036_fundtransfermodel_date_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.fundmodel', verbose_name='Associated Fund'),
        ),
        migrations.AddIndex(
            model_name='transactionmodel',
            index=models.Index(fields=['fund'], name='django_ledg_fund_id_ceaefc_idx'),
        ),
    ]
