# Generated by Django 5.1.6 on 2025-05-22 21:06

from django.db import migrations


def migrate_funds_forward(apps, schema_editor):
    """
    Copy fund values from JournalEntryModel to TransactionModel for all existing transactions.

    Logic:
    - If journal_entry.receiving_fund is null, then transaction.fund = journal_entry.fund
    - If journal_entry.receiving_fund is not null, then:
      - If transaction.tx_type is 'credit', then transaction.fund = journal_entry.fund
      - If transaction.tx_type is 'debit', then transaction.fund = journal_entry.receiving_fund
    """
    TransactionModel = apps.get_model('django_ledger', 'TransactionModel')

    # Use raw SQL for better performance with large datasets
    schema_editor.execute(
        """
        UPDATE django_ledger_transactionmodel
        SET fund_id = CASE
            -- If receiving_fund is null, use journal_entry.fund
            WHEN django_ledger_journalentrymodel.receiving_fund_id IS NULL THEN django_ledger_journalentrymodel.fund_id
            -- If receiving_fund is not null and tx_type is 'credit', use journal_entry.fund
            WHEN django_ledger_journalentrymodel.receiving_fund_id IS NOT NULL AND django_ledger_transactionmodel.tx_type = 'credit' THEN django_ledger_journalentrymodel.fund_id
            -- If receiving_fund is not null and tx_type is 'debit', use journal_entry.receiving_fund
            WHEN django_ledger_journalentrymodel.receiving_fund_id IS NOT NULL AND django_ledger_transactionmodel.tx_type = 'debit' THEN django_ledger_journalentrymodel.receiving_fund_id
        END
        FROM django_ledger_journalentrymodel
        WHERE django_ledger_transactionmodel.journal_entry_id = django_ledger_journalentrymodel.uuid
        AND (
            django_ledger_journalentrymodel.fund_id IS NOT NULL
            OR django_ledger_journalentrymodel.receiving_fund_id IS NOT NULL
        )
        """
    )


def migrate_funds_backward(apps, schema_editor):
    """
    No need to migrate backward as we're keeping the fund field in JournalEntryModel for now.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0037_add_fund_to_transaction'),
    ]

    operations = [
        migrations.RunPython(
            migrate_funds_forward,
            migrate_funds_backward
        ),
    ]
