# Generated by Django 5.1.6 on 2025-05-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0038_migrate_fund_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journalentrymodel',
            name='django_ledg_fund_id_289e56_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentrymodel',
            name='django_ledg_receivi_09a074_idx',
        ),
    ]
