# Generated by Django 5.1.6 on 2025-05-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0039_remove_journalentrymodel_django_ledg_fund_id_289e56_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentrymodel',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='journalentrymodel',
            name='receiving_fund',
        ),
    ]
